[package]
name = "Conny"
authors = ["Nika <nika@nikableh.moe>"]
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.0", package = "gtk4", features = ["gnome_48", "blueprint"] }
